server:
 port: 8001

spring:  
  jpa:  
    hibernate:  
      ddl-auto: update  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/MicroservicePOC"  
    username: postgres  
    password: manager
  application:    name: DEPARTMENT-SERVICE
  zipkin:
   base-url: http://localhost:9411/