server:
 port: 8002

spring:  
  jpa:  
    hibernate:  
      ddl-auto: update  
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  datasource:  
    url: "jdbc:postgresql://localhost:5432/MicroservicePOC"  
    username: postgres  
    password: manager
  application:    name: USER-SERVICE